[package]
name = "keepass"
description = "KeePass .kdbx database file parser"

homepage = "https://github.com/sseemayer/keepass-rs"
repository = "https://github.com/sseemayer/keepass-rs"
documentation = "https://sseemayer.github.io/keepass-rs/"

version = "0.1.2"
authors = ["Stefan Seemayer <stefan@seemayer.de>"]
license = "MIT"

readme = "README.md"

[dependencies]
byteorder = "^1.0.0"
flate2 = "^0.2.13"
rust-crypto = "^0.2.34"
secstr = "^0.3.0"
xml-rs = "^0.6.0"
rustc-serialize = "^0.3.16"
